# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'FlickrSearch' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for FlickrSearch
  
  pod 'Overcoat', '~> 3.2.1'
  pod 'DZNEmptyDataSet'
  pod 'SDWebImage', '~> 3.7.3'
  pod 'AFNetworkActivityLogger', '~> 2.0.4'

end
